time_blocks = [
    { name = "Morning Work", start_time = "08:00", end_time = "12:00" },
    { name = "Lunch Break", start_time = "12:00", end_time = "13:00" },
    { name = "Afternoon Work", start_time = "13:00", end_time = "17:00" }
]
